name: Fetch GitHub User Data

on:
  push:
    branches:
      - main

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch GitHub User Data
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/micaelparadox > data.json
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data.json
        git commit -m "Add GitHub user data"
        git push
